name: brand-guard
on: [pull_request]
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if rg -n --hidden --glob '!node_modules' --glob '!dist' -e 'XORB|Xorb|xorb' .; then
            echo "❌ Found deprecated brand tokens."; exit 1; fi